---
title: Some Common Biostatistics Formulae
author: 'Saikat Roy'
date: '2021-07-20'
slug: []
categories:
  - "Biostatistics"
tags:
  - Odds ratio
  - Relative Risk
subtitle: ''
lastmod: '2021-07-20T09:19:40Z'
description: "I have explained some of the commonly used formulae in Biostatistics."
page:
  theme: wide
upd: ''
authorComment: ''
hiddenFromHomePage: no
hiddenFromSearch: no
resources:
  name: featured-image
  src: featured-image.jpg
featuredImage: ''
featuredImagePreview: ''
images:
  - ''
toc:
  enable: yes
math:
  enable: yes
license: ''
draft: true
---
I have explained some of the commonly used categorical data analysis formulae and concepts behind these formulae in Biostatistics in this post.
<!--more-->

This post contains some commonly used formulae in categorical data analysis. These concepts are often used in contexts other than Biostatistics. So it'll not be correct to specifically say that these are Biostatistics fomulae. However, all the examples I have used here are often used in Biostatistics.


### 1. Risk

Risk indicates the likelihood of an event occurring. This is similar to the concepts of proportion and probability. 

$$
\text{Risk of an event } \mathcal{A}= \text{The probability or the likelihood that the event $\mathcal{A}$ will occur } = \frac{\text{number of outcome of event }\mathcal{A}}{\text{total number of outcomes}}
$$

$$
\pi = \frac{n(\mathcal{A})}{\mathcal{N}}
$$

40 out of 1000 children have jaundice.

$$
risk ~of~ children~ having~ jaundice= \frac{40}{1000} = 0.04
$$

This means that  4% of the children suffer from jaundice.

Observe that the formulae of risk, likelihood and probability are similar.

### 2. Relative Risk

The relative risk of an event is a comparison of two risks of the event at two different situations of another event. The relative risk, $\rho$ of the success of an event A (1 denotes success) at two levels (1 and 2) of another event B,

$$
\rho = \frac{P(A=1|B=1)}{P(A=1|B=2)}
$$

The denominator of the term above is the **baseline risk**. It is the risk with which the comparison is being made.


https://online.stat.psu.edu/stat504/lesson/3/3.1/3.1.8

https://online.stat.psu.edu/stat200/lesson/2/2.1/2.1.1/2.1.1.1

https://online.stat.psu.edu/stat800/lesson/6/6.3